### ISSUE TITLE
keras to opencv file format issue

### ISSUE THREAD

**Issue by elnas** [ChunML/DeepLearning#1]
# I am faced with the following error while trying to run camera.py script. I guess it is a keras to opencv file format issue and I don't know how to solve it.

> ValueError: Error when checking : expected input_1 to have shape (None, 224, 224, 3) but got array with shape (1, 3, 224, 224)
![screenshot 2017-09-05 22 06 28](https://user-images.githubusercontent.com/4264002/30083492-814d31d0-9286-11e7-8c15-45768383c69f.png)

**Comment by SJameer** [comment]
When running the test_imagenet.py getting the error like
![screenshot from 2017-09-19 16-17-49](https://user-images.githubusercontent.com/19899289/30588885-1a89f502-9d56-11e7-9914-75d4af70c7b2.png)

Can any one please update why getting the error

**Comment by ManjeeraJagiri** [comment]
@elnas , you can try commenting the following line of the code ```image = image.transpose((2, 0, 1))```

**Comment by elnas** [comment]
@ManjeeraJagiri  thanx a millie. Problem solved!!!
